### ISSUE TITLE
Possible to only show human players and not bots?

### ISSUE THREAD

**Issue by ghost** [JoinedSenses/TF2-ServerHop#7]
Title: currently %numplayers also include bot players. I would like to only show human players. Thanks.

**Comment by JoinedSenses** [comment]
Maybe, though I have no interest right now in learning how to write source server queries. This plugin isn't really supported for new features from me unless it is game breaking (especially since I'm not the original author), so anyone is free to submit a PR with a player query and a convar to allow filtering bots.

**Comment by JoinedSenses** [comment]
I've only quickly glanced over the current query response, and bots appears to be a part of it. If it's as easy as it looks, I may be able to implement it.

**Comment by ghost** [comment]
Take your time, and if possible add %botplayers and %humanplayers instead of replacing %numplayers. Thanks!

**Comment by JoinedSenses** [comment]
Sure.
